export const courses = [
  {
    name: 'The Complete Web Development in 2022',
    id: 'the-complete-web-development-in-2022',
    img: '/images/courses/web-dev.jpg',

    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 333,
      discount: 83,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'The Complete App Development in 2022',
    id: 'the-complete-app-development-in-2022',
    img: '/images/courses/mobile-dev.jpg',

    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 333,
      discount: 83,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'Product Design',
    id: 'product-design',
    img: '/images/courses/uiux.jpg',

    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 100,
      discount: 33,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'Graphics Design',
    id: 'graphics-design',
    img: '/images/courses/graphic-design.jpg',
    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 67,
      discount: 17,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'Graphics Design Using Mobile Phone',
    id: 'graphics-design-mobile',
    img: '/images/courses/graphics-design-mobile.jpg',
    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 25,
      discount: 8,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'Digital Marketing',
    id: 'digital-marketing',
    img: '/images/courses/digital-marketing.jpg',

    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 58,
      discount: 16,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'Copy Writing',
    id: 'copy-writing',
    img: '/images/courses/copy-writing.jpg',
    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 33,
      discount: 8,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'Auto-CAD Design',
    id: 'auto-cad-design',
    img: '/images/courses/auto-cad.jpg',

    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 100,
      discount: 33,
      USD_NGN_RATE: 600,
    },
  },
  {
    name: 'Auto-CAD Design (3D)',
    id: 'auto-cad-design-3d',
    img: '/images/courses/auto-cad-3d.jpg',

    overview:
      'This course is designed to teach you the latest web development technologies and best practices.',
    description:
      "Learn to code. Get hired. This is one of the most popular,  highly rated coding boot-camps online. It's also the most modern  and up-to-date. Guaranteed. You'll go from complete beginner to  learning to code and getting hired as a Developer (this year!) at companies like Google, Tesla, and Amazon.",
    what_you_learn: [
      'Master modern Web Development fundamentals as well as advanced topics',
      'Master fundamental concepts in Web Development',
      'Learn best practices to write clean, performant, and bug free code',
      'Build 10+ real world Web Development projects you can show off on your portfolio',
      'Use NodeJS to write server-side JavaScript',
      'Learn modern technologies that are ACTUALLY being used at tech companies in 2022',
      'Build a professional Portfolio Website',
    ],
    course_curriculum: [
      'How The Internet Works',
      'History Of The Web',
      'HTML5',
      'Advanced HTML 5',
      'CSS',
      'Advanced CSS',
      'Css frameworks; bootstrap, tailwindcss and sass.',
      'JavaScript',
      'Advanced JavaScript',
      'JavaScript frameworks',
      'NodeJS',
      'ExpressJs for building backend',
      'Advanced ExpressJs',
      'React',
      'ReactJs',
      'Redux,React Query, GraphQl',
      'Advanced ReactJs',
      'Career of a web developer',
    ],
    take_away: [
      '1-1 mentorship(lifetime) 😎.',
      'How to earn money as a developer.',
    ],
    prerequisites: [
      'A willingness and enthusiasm to learn',
      'A computer (Windows, Mac, or Linux) with an internet connection',
    ],
    price: {
      currency: 'USD',
      price: 100,
      discount: 33,
      USD_NGN_RATE: 600,
    },
  },
];
